#
spring:
  datasource:
    url: jdbc:postgresql://xxx.xxx.xxx.xxx:5432/jdevtemplatepostgre
    driver-class-name: org.postgresql.Driver
    username: xxxxxxx
    password: ENC(BLmpgEmFWHwUgeJbDf849Q==)

