#
spring:
  datasource:
    url: jdbc:sqlserver://xxx.xxx.xxx.xxx:1433; DatabaseName=test
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: xxxxxxx
    password: ENC(BLmpgEmFWHwUgeJbDf849Q==)

