spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化，最小，最大连接数
    initialSize: 3
    minidle: 10
    maxActive: 10
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM dual
    # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计
    filters: stat,wall,log4j
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.itstyle.database.domain.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl